theme = "monokai"

[editor]
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# "C-tab" = "goto_next_buffer"
"C-tab" = "rotate_view"

[editor.cursor-shape]
insert = "bar"


